<?php

namespace Tryout\CabinetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactProfileRepository extends EntityRepository
{
}
