<?php

namespace Tryout\CabinetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuickProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuickProfileRepository extends EntityRepository
{
	public function findOwnerOfQuickProfileByVendorId($vendorId){
    	
    return $this->createQueryBuilder('q')
        ->andWhere('q.vendor = :vendorId')
        ->setParameter('vendorId', $vendorId)
        ->getQuery()
    	->execute()
    ;		
		
	}
	
}
