<?php

namespace Tryout\CabinetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorRepository extends EntityRepository
{
    /**
     * Find Vendors who belong to the the current 
	 * user
     *
     */
	public function findOwnerOfVendorEntityByUserID($id){
    	
    return $this->createQueryBuilder('v')
        ->andWhere('v.ownerOfVendorEntity = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getOneOrNullResult()
    	//->execute()
    ;
		
	}

	public function findOneByIdJoinedToCategory($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT v, o FROM CabinetBundle:Vendor v
            	JOIN v.ownerOfVendorEntity o
	            WHERE o.id = :id'
	        )->setParameter('id', $id);
	
	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}	
	
	public function findOneVendorProfileById($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery('
	            SELECT v, vp FROM CabinetBundle:Vendor v
            	JOIN v.vendorProfiles vp
	            WHERE vp.vendor = :id'
	        )->setParameter('id', $id);
	
	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}	
	
}
