services:      
    tryout_user.listener.add_vendor_role:
        class: Tryout\UserBundle\Listener\AddVendorRoleListener
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: kernel.event_subscriber }      
    tryout_user.registration.form.type:
        class: Tryout\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tryout_user_registration }
        